package com.wang.study.photositejava.bean;

import java.util.Date;

public class PsComments {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.comment_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Long commentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.photo_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Long photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.comment_date
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Date commentDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.comment_karma
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Integer commentKarma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.comment_approved
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private String commentApproved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.comment_agent
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private String commentAgent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.comment_type
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private String commentType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.user_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.user_name
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_comments.comment_content
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private String commentContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.comment_id
     *
     * @return the value of ps_comments.comment_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Long getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.comment_id
     *
     * @param commentId the value for ps_comments.comment_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setCommentId(Long commentId) {
        this.commentId = commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.photo_id
     *
     * @return the value of ps_comments.photo_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.photo_id
     *
     * @param photoId the value for ps_comments.photo_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.comment_date
     *
     * @return the value of ps_comments.comment_date
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Date getCommentDate() {
        return commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.comment_date
     *
     * @param commentDate the value for ps_comments.comment_date
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setCommentDate(Date commentDate) {
        this.commentDate = commentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.comment_karma
     *
     * @return the value of ps_comments.comment_karma
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Integer getCommentKarma() {
        return commentKarma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.comment_karma
     *
     * @param commentKarma the value for ps_comments.comment_karma
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setCommentKarma(Integer commentKarma) {
        this.commentKarma = commentKarma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.comment_approved
     *
     * @return the value of ps_comments.comment_approved
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public String getCommentApproved() {
        return commentApproved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.comment_approved
     *
     * @param commentApproved the value for ps_comments.comment_approved
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setCommentApproved(String commentApproved) {
        this.commentApproved = commentApproved == null ? null : commentApproved.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.comment_agent
     *
     * @return the value of ps_comments.comment_agent
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public String getCommentAgent() {
        return commentAgent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.comment_agent
     *
     * @param commentAgent the value for ps_comments.comment_agent
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setCommentAgent(String commentAgent) {
        this.commentAgent = commentAgent == null ? null : commentAgent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.comment_type
     *
     * @return the value of ps_comments.comment_type
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public String getCommentType() {
        return commentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.comment_type
     *
     * @param commentType the value for ps_comments.comment_type
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setCommentType(String commentType) {
        this.commentType = commentType == null ? null : commentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.user_id
     *
     * @return the value of ps_comments.user_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.user_id
     *
     * @param userId the value for ps_comments.user_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.user_name
     *
     * @return the value of ps_comments.user_name
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.user_name
     *
     * @param userName the value for ps_comments.user_name
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_comments.comment_content
     *
     * @return the value of ps_comments.comment_content
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public String getCommentContent() {
        return commentContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_comments.comment_content
     *
     * @param commentContent the value for ps_comments.comment_content
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setCommentContent(String commentContent) {
        this.commentContent = commentContent == null ? null : commentContent.trim();
    }
    /**
     * toString 方法
     * */
    @Override
    public  String toString(){
        StringBuilder re = new StringBuilder();
        re.append(getClass().getSimpleName());
        re.append("[");
        re.append(", Hash = ").append(hashCode());
        re.append(", comment_id = ").append(getCommentId());
        re.append(", photo_id = ").append(getPhotoId());
        re.append(", comment_date = ").append(getCommentDate().toString());
        re.append(", comment_content = ").append(getCommentContent());
        re.append(", comment_karma = ").append(getCommentKarma());
        re.append(", comment_approved = ").append(getCommentApproved());
        re.append(", comment_agent = ").append(getCommentAgent());
        re.append(", comment_type = ").append(getCommentType());
        re.append(", user_id = ").append(getUserId());
        re.append(", user_name = ").append(getUserName());
        re.append("]");
        return re.toString();
    }
}