package com.wang.study.photositejava.bean;

import java.util.Date;

public class PsPhotos {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String photoName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_address
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String photoAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_width
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Integer photoWidth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_height
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Integer photoHeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.user_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_format
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String photoFormat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_eigenvalues
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String photoEigenvalues;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_topic_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long photoTopicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_big_address
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String photoBigAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_media_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long photoMediaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_photos.photo_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String photoMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_id
     *
     * @return the value of ps_photos.photo_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_id
     *
     * @param photoId the value for ps_photos.photo_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_name
     *
     * @return the value of ps_photos.photo_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getPhotoName() {
        return photoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_name
     *
     * @param photoName the value for ps_photos.photo_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoName(String photoName) {
        this.photoName = photoName == null ? null : photoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_address
     *
     * @return the value of ps_photos.photo_address
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getPhotoAddress() {
        return photoAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_address
     *
     * @param photoAddress the value for ps_photos.photo_address
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoAddress(String photoAddress) {
        this.photoAddress = photoAddress == null ? null : photoAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_width
     *
     * @return the value of ps_photos.photo_width
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Integer getPhotoWidth() {
        return photoWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_width
     *
     * @param photoWidth the value for ps_photos.photo_width
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoWidth(Integer photoWidth) {
        this.photoWidth = photoWidth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_height
     *
     * @return the value of ps_photos.photo_height
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Integer getPhotoHeight() {
        return photoHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_height
     *
     * @param photoHeight the value for ps_photos.photo_height
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoHeight(Integer photoHeight) {
        this.photoHeight = photoHeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.user_id
     *
     * @return the value of ps_photos.user_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.user_id
     *
     * @param userId the value for ps_photos.user_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_format
     *
     * @return the value of ps_photos.photo_format
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getPhotoFormat() {
        return photoFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_format
     *
     * @param photoFormat the value for ps_photos.photo_format
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoFormat(String photoFormat) {
        this.photoFormat = photoFormat == null ? null : photoFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_eigenvalues
     *
     * @return the value of ps_photos.photo_eigenvalues
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getPhotoEigenvalues() {
        return photoEigenvalues;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_eigenvalues
     *
     * @param photoEigenvalues the value for ps_photos.photo_eigenvalues
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoEigenvalues(String photoEigenvalues) {
        this.photoEigenvalues = photoEigenvalues == null ? null : photoEigenvalues.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_topic_id
     *
     * @return the value of ps_photos.photo_topic_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getPhotoTopicId() {
        return photoTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_topic_id
     *
     * @param photoTopicId the value for ps_photos.photo_topic_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoTopicId(Long photoTopicId) {
        this.photoTopicId = photoTopicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_big_address
     *
     * @return the value of ps_photos.photo_big_address
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getPhotoBigAddress() {
        return photoBigAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_big_address
     *
     * @param photoBigAddress the value for ps_photos.photo_big_address
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoBigAddress(String photoBigAddress) {
        this.photoBigAddress = photoBigAddress == null ? null : photoBigAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_media_id
     *
     * @return the value of ps_photos.photo_media_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getPhotoMediaId() {
        return photoMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_media_id
     *
     * @param photoMediaId the value for ps_photos.photo_media_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoMediaId(Long photoMediaId) {
        this.photoMediaId = photoMediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.create_time
     *
     * @return the value of ps_photos.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.create_time
     *
     * @param createTime the value for ps_photos.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_photos.photo_message
     *
     * @return the value of ps_photos.photo_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getPhotoMessage() {
        return photoMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_photos.photo_message
     *
     * @param photoMessage the value for ps_photos.photo_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoMessage(String photoMessage) {
        this.photoMessage = photoMessage == null ? null : photoMessage.trim();
    }
}