package com.wang.study.photositejava.bean;

import java.util.Date;

public class PsTargets {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_targets.target_link_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long targetLinkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_targets.target_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String targetName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_targets.photo_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Integer photoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_targets.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_targets.target_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String targetMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_targets.target_link_id
     *
     * @return the value of ps_targets.target_link_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getTargetLinkId() {
        return targetLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_targets.target_link_id
     *
     * @param targetLinkId the value for ps_targets.target_link_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setTargetLinkId(Long targetLinkId) {
        this.targetLinkId = targetLinkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_targets.target_name
     *
     * @return the value of ps_targets.target_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_targets.target_name
     *
     * @param targetName the value for ps_targets.target_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setTargetName(String targetName) {
        this.targetName = targetName == null ? null : targetName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_targets.photo_id
     *
     * @return the value of ps_targets.photo_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Integer getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_targets.photo_id
     *
     * @param photoId the value for ps_targets.photo_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setPhotoId(Integer photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_targets.create_time
     *
     * @return the value of ps_targets.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_targets.create_time
     *
     * @param createTime the value for ps_targets.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_targets.target_message
     *
     * @return the value of ps_targets.target_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getTargetMessage() {
        return targetMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_targets.target_message
     *
     * @param targetMessage the value for ps_targets.target_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setTargetMessage(String targetMessage) {
        this.targetMessage = targetMessage == null ? null : targetMessage.trim();
    }
}