package com.wang.study.photositejava.bean;

import java.util.Date;

public class PsTopics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_topics.topic_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long topicId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_topics.topic_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String topicName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_topics.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_topics.display_photo_little_url
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String displayPhotoLittleUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_topics.topic_target
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String topicTarget;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_topics.display_photo_url
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String displayPhotoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_topics.topic_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String topicMessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_topics.topic_id
     *
     * @return the value of ps_topics.topic_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_topics.topic_id
     *
     * @param topicId the value for ps_topics.topic_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setTopicId(Long topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_topics.topic_name
     *
     * @return the value of ps_topics.topic_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_topics.topic_name
     *
     * @param topicName the value for ps_topics.topic_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_topics.create_time
     *
     * @return the value of ps_topics.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_topics.create_time
     *
     * @param createTime the value for ps_topics.create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_topics.display_photo_little_url
     *
     * @return the value of ps_topics.display_photo_little_url
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getDisplayPhotoLittleUrl() {
        return displayPhotoLittleUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_topics.display_photo_little_url
     *
     * @param displayPhotoLittleUrl the value for ps_topics.display_photo_little_url
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setDisplayPhotoLittleUrl(String displayPhotoLittleUrl) {
        this.displayPhotoLittleUrl = displayPhotoLittleUrl == null ? null : displayPhotoLittleUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_topics.topic_target
     *
     * @return the value of ps_topics.topic_target
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getTopicTarget() {
        return topicTarget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_topics.topic_target
     *
     * @param topicTarget the value for ps_topics.topic_target
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setTopicTarget(String topicTarget) {
        this.topicTarget = topicTarget == null ? null : topicTarget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_topics.display_photo_url
     *
     * @return the value of ps_topics.display_photo_url
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getDisplayPhotoUrl() {
        return displayPhotoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_topics.display_photo_url
     *
     * @param displayPhotoUrl the value for ps_topics.display_photo_url
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setDisplayPhotoUrl(String displayPhotoUrl) {
        this.displayPhotoUrl = displayPhotoUrl == null ? null : displayPhotoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_topics.topic_message
     *
     * @return the value of ps_topics.topic_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getTopicMessage() {
        return topicMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_topics.topic_message
     *
     * @param topicMessage the value for ps_topics.topic_message
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setTopicMessage(String topicMessage) {
        this.topicMessage = topicMessage == null ? null : topicMessage.trim();
    }
}