package com.wang.study.photositejava.bean;

public class PsUserFavorites {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites.favorites_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Long favoritesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites.folder_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Long folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites.user_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites.photo_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    private Long photoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites.favorites_id
     *
     * @return the value of ps_user_favorites.favorites_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Long getFavoritesId() {
        return favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites.favorites_id
     *
     * @param favoritesId the value for ps_user_favorites.favorites_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setFavoritesId(Long favoritesId) {
        this.favoritesId = favoritesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites.folder_id
     *
     * @return the value of ps_user_favorites.folder_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Long getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites.folder_id
     *
     * @param folderId the value for ps_user_favorites.folder_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setFolderId(Long folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites.user_id
     *
     * @return the value of ps_user_favorites.user_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites.user_id
     *
     * @param userId the value for ps_user_favorites.user_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites.photo_id
     *
     * @return the value of ps_user_favorites.photo_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public Long getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites.photo_id
     *
     * @param photoId the value for ps_user_favorites.photo_id
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    public void setPhotoId(Long photoId) {
        this.photoId = photoId;
    }
    /**
     * toString
     * */
    @Override
    public  String toString(){
        StringBuilder re = new StringBuilder();
        re.append(getClass().getSimpleName());
        re.append("[");
        re.append(", Hash = ").append(hashCode());
        re.append(", favorites_id = ").append(getFavoritesId());
        re.append(", folder_id = ").append(getFolderId());
        re.append(", user_id = ").append(getUserId());
        re.append(", photo_id = ").append(getPhotoId());
        re.append("]");
        return re.toString();
    }
}