package com.wang.study.photositejava.bean;

import java.util.Date;

public class PsUserFavoritesFolder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites_folder.folder_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long folderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites_folder.folder_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private String folderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites_folder.user_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ps_user_favorites_folder.folder_create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    private Date folderCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites_folder.folder_id
     *
     * @return the value of ps_user_favorites_folder.folder_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getFolderId() {
        return folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites_folder.folder_id
     *
     * @param folderId the value for ps_user_favorites_folder.folder_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setFolderId(Long folderId) {
        this.folderId = folderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites_folder.folder_name
     *
     * @return the value of ps_user_favorites_folder.folder_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public String getFolderName() {
        return folderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites_folder.folder_name
     *
     * @param folderName the value for ps_user_favorites_folder.folder_name
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setFolderName(String folderName) {
        this.folderName = folderName == null ? null : folderName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites_folder.user_id
     *
     * @return the value of ps_user_favorites_folder.user_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites_folder.user_id
     *
     * @param userId the value for ps_user_favorites_folder.user_id
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ps_user_favorites_folder.folder_create_time
     *
     * @return the value of ps_user_favorites_folder.folder_create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public Date getFolderCreateTime() {
        return folderCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ps_user_favorites_folder.folder_create_time
     *
     * @param folderCreateTime the value for ps_user_favorites_folder.folder_create_time
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    public void setFolderCreateTime(Date folderCreateTime) {
        this.folderCreateTime = folderCreateTime;
    }
}