

spring:
  profiles:
    active: dev
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss



mybatis:
  mapperLocations: classpath:mapper/*.xml
  configLocation: classpath:mybatis.xml
  type-aliases-package: com.wang.study.photositejava.bean # 指定bean配置实体


##1.项目启动的端口
#server.port=18902
#
##2.数据库连接参数
##2.1jdbc驱动，示数据库厂商决定，这是mysql的驱动
#jdbc.driver=com.mysql.cj.jdbc.Driver
##2.2数据库连接url，包括ip(127.0.0.1)、端口(3306)、数据库名(testdb)
#jdbc.url=jdbc:mysql://127.0.0.1:3306/photo_site?useUnicode=true&characterEncoding=utf-8&useSSL=false
##2.3数据库账号名
#jdbc.username=root
##2.4数据库密码
#jdbc.password=123456

#3.Mybatis配置
#3.1 mybatis配置文件所在路径
#mybatis_config_file=mybatis.xml
##3.2 mapper文件所在路径，这样写可匹配mapper目录下的所有mapper，包括其子目录下的
#mapper_path=/mapper/**/**.xml
##3.3 entity所在包
##entity_package=cn.stephen.study.demoproject.entity
#entity_package=com.wang.study.photositejava.entity