# 服务器设置
server:
  port: 8080

# spring设置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/photo_site?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: peng
    password: peng
    driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
  # tomcats设置
  tomcat:
    initialSize: 1
    min-idle: 1
    max-idle: 20
    max-wait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.wang.study.photositejava: DEBUG