package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsComments;
import java.util.List;

public interface PsCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_comments
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    int insert(PsComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_comments
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    List<PsComments> selectAll();
}