package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsLoadHistory;
import java.util.List;

public interface PsLoadHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_load_history
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    int insert(PsLoadHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_load_history
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    List<PsLoadHistory> selectAll();
}