package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsPhotos;
import java.util.List;

public interface PsPhotosMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_photos
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    int insert(PsPhotos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_photos
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    List<PsPhotos> selectAll();
}