package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsTargets;
import java.util.List;

public interface PsTargetsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_targets
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    int insert(PsTargets record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_targets
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    List<PsTargets> selectAll();
}