package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsTopics;
import java.util.List;

public interface PsTopicsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_topics
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    int insert(PsTopics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_topics
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    List<PsTopics> selectAll();
}