package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsUsers;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PsUsersMapper {
    /**
     *
     * 根据主键删除数据库中的记录
     * @param  id
     * */
    int deleteByPrimaryKey(Long id);
    /**
     * 根据主键进行查找
     * @param  id
     * */
    void selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    int insert(PsUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_users
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    List<PsUsers> selectAll();
    /**
     * 根据主键来更新数据库记录
     *
     * @param record
     */
    int updateByPrimaryKey(PsUsers record);
    /**
     * 根据用户id 更新密码
     * @param userId
     * @param password
     * */
    int updatePassword(@Param("id")Long userId, @Param("pwd")String password);
    /**
     * 根据用户名和密码查找用户
     * @param username
     * @param password
     * */
    PsUsers findByUsernameAndPassword(@Param("username") String username, @Param("pwd") String password);
    /**
     * 根据用户名查找
     * @param username
     *
     * */
    PsUsers findByUsername(String username);
    /**
     * 根据id删除用户
     * @param id
     * */
    PsUsers selectDeleteUser(Long id);


}