package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsUserBrowserecord;
import java.util.List;

public interface PsUserBrowserecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user_browserecord
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    int insert(PsUserBrowserecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user_browserecord
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    List<PsUserBrowserecord> selectAll();
}