package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsUserFavoritesFolder;
import java.util.List;

public interface PsUserFavoritesFolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user_favorites_folder
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    int insert(PsUserFavoritesFolder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user_favorites_folder
     *
     * @mbg.generated Fri May 29 18:16:33 CST 2020
     */
    List<PsUserFavoritesFolder> selectAll();
}