package com.wang.study.photositejava.dao;

import com.wang.study.photositejava.bean.PsUserFavorites;
import java.util.List;

public interface PsUserFavoritesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user_favorites
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    int insert(PsUserFavorites record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ps_user_favorites
     *
     * @mbg.generated Thu May 28 08:55:18 CST 2020
     */
    List<PsUserFavorites> selectAll();
}